# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

sudo: required
language: minimal
services:
  - docker

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: docker-compose build

jobs:
  include:
    - stage: deploy
      script: ./drun_app python main.py

