# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

sudo: required
language: minimal
services:
  - docker

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: docker-compose build

jobs:
  include:
    - stage: test
      # Command to run tests, e.g. python setup.py test
      script: ./drun_app pytest
    - stage: utiltest
      script: ./drun_app pytest pset_utils      
    - stage: deploy
      if: branch = master
      script: ./drun_app python main.py

